// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_categories_index from "./routes/api/categories/index.ts";
import * as $api_expenses_id_ from "./routes/api/expenses/[id].ts";
import * as $api_expenses_date from "./routes/api/expenses/date.ts";
import * as $api_expenses_index from "./routes/api/expenses/index.ts";
import * as $api_income_id_ from "./routes/api/income/[id].ts";
import * as $api_income_date from "./routes/api/income/date.ts";
import * as $api_income_index from "./routes/api/income/index.ts";
import * as $api_payment_methods_index from "./routes/api/payment-methods/index.ts";
import * as $app from "./routes/app.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $AddExpenseButton from "./islands/AddExpenseButton.tsx";
import * as $AddIncomeButton from "./islands/AddIncomeButton.tsx";
import * as $AppButton from "./islands/AppButton.tsx";
import * as $AuthButton from "./islands/AuthButton.tsx";
import * as $BackButton from "./islands/BackButton.tsx";
import * as $CardTitle from "./islands/CardTitle.tsx";
import * as $EditIncomeButton from "./islands/EditIncomeButton.tsx";
import * as $InputSelector from "./islands/InputSelector.tsx";
import * as $Loader from "./islands/Loader.tsx";
import * as $Menu from "./islands/Menu.tsx";
import * as $Stats from "./islands/Stats.tsx";
import * as $ThemeController from "./islands/ThemeController.tsx";
import * as $forms_ExpenseForm from "./islands/forms/ExpenseForm.tsx";
import * as $forms_IncomeForm from "./islands/forms/IncomeForm.tsx";
import * as $hooks_useModal from "./islands/hooks/useModal.tsx";
import * as $tables_ExpenseOptionsButton from "./islands/tables/ExpenseOptionsButton.tsx";
import * as $tables_ExpensesTable from "./islands/tables/ExpensesTable.tsx";
import * as $tables_IncomeOptionsButton from "./islands/tables/IncomeOptionsButton.tsx";
import * as $tables_IncomeTable from "./islands/tables/IncomeTable.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/categories/index.ts": $api_categories_index,
    "./routes/api/expenses/[id].ts": $api_expenses_id_,
    "./routes/api/expenses/date.ts": $api_expenses_date,
    "./routes/api/expenses/index.ts": $api_expenses_index,
    "./routes/api/income/[id].ts": $api_income_id_,
    "./routes/api/income/date.ts": $api_income_date,
    "./routes/api/income/index.ts": $api_income_index,
    "./routes/api/payment-methods/index.ts": $api_payment_methods_index,
    "./routes/app.tsx": $app,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/AddExpenseButton.tsx": $AddExpenseButton,
    "./islands/AddIncomeButton.tsx": $AddIncomeButton,
    "./islands/AppButton.tsx": $AppButton,
    "./islands/AuthButton.tsx": $AuthButton,
    "./islands/BackButton.tsx": $BackButton,
    "./islands/CardTitle.tsx": $CardTitle,
    "./islands/EditIncomeButton.tsx": $EditIncomeButton,
    "./islands/InputSelector.tsx": $InputSelector,
    "./islands/Loader.tsx": $Loader,
    "./islands/Menu.tsx": $Menu,
    "./islands/Stats.tsx": $Stats,
    "./islands/ThemeController.tsx": $ThemeController,
    "./islands/forms/ExpenseForm.tsx": $forms_ExpenseForm,
    "./islands/forms/IncomeForm.tsx": $forms_IncomeForm,
    "./islands/hooks/useModal.tsx": $hooks_useModal,
    "./islands/tables/ExpenseOptionsButton.tsx": $tables_ExpenseOptionsButton,
    "./islands/tables/ExpensesTable.tsx": $tables_ExpensesTable,
    "./islands/tables/IncomeOptionsButton.tsx": $tables_IncomeOptionsButton,
    "./islands/tables/IncomeTable.tsx": $tables_IncomeTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
