import { type Config } from "tailwindcss";
import daisyui from "daisyui";

export default {
  content: ["{routes,islands,components}/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        latte: {
          rosewater: "#dc8a78",
          flamingo: "#DD7878",
          pink: "#ea76cb",
          mauve: "#8839ef",
          red: "#D20F39",
          maroon: "#E64553",
          peach: "#FE640B",
          yellow: "#df8e1d",
          green: "#40A02B",
          teal: "#179299",
          sky: "#04A5E5",
          sapphire: "#209FB5",
          blue: "#1e66f5",
          lavender: "#7287fd",
          text: "#4C4F69",
          subtext1: "#5C5F77",
          subtext0: "#6C6F85",
          overlay2: "#7C7F93",
          overlay1: "#8C8FA1",
          overlay0: "#9CA0B0",
          surface2: "#ACB0BE",
          surface1: "#BCC0CC",
          surface0: "#CCD0DA",
          base: "#EFF1F5",
          mantle: "#E6E9EF",
          crust: "#DCE0E8",
        },
        macchiato: {
          rosewater: "#F4DBD6",
          flamingo: "#F0C6C6",
          pink: "#F5BDE6",
          mauve: "#C6A0F6",
          red: "#ED8796",
          maroon: "#EE99A0",
          peach: "#F5A97F",
          yellow: "#EED49F",
          green: "#A6DA95",
          teal: "#8BD5CA",
          sky: "#91D7E3",
          sapphire: "#7DC4E4",
          blue: "#8AADF4",
          lavender: "#B7BDF8",
          text: "#CAD3F5",
          subtext1: "#B8C0E0",
          subtext0: "#A5ADCB",
          overlay2: "#939AB7",
          overlay1: "#8087A2",
          overlay0: "#6E738D",
          surface2: "#5B6078",
          surface1: "#494D64",
          surface0: "#363A4F",
          base: "#24273A",
          mantle: "#1E2030",
          crust: "#181926",
        },
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    logs: false,
    darkTheme: "macchiato",
    themes: [
      {
        latte: {
          primary: "#1e66f5",
          secondary: "#FE640B",
          accent: "#8839ef",
          neutral: "#EFF1F5",
          "base-100": "#ffffff",
          info: "#04A5E5",
          success: "#40A02B",
          warning: "#df8e1d",
          error: "#D20F39",
        },
      },
      {
        macchiato: {
          primary: "#8AADF4",
          secondary: "#F5A97F",
          accent: "#C6A0F6",
          neutral: "#1E2030",
          "base-100": "#24273A",
          info: "#91D7E3",
          success: "#A6DA95",
          warning: "#EED49F",
          error: "#ED8796",
        },
      },
    ],
  },
} satisfies Config;
